name: Release (Windows)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build portable EXE (PyInstaller)
        shell: powershell
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon app.ico --name SecurePasteP2P secure.py
          if (!(Test-Path dist\SecurePasteP2P.exe)) { throw "Portable exe not found at dist\\SecurePasteP2P.exe" }

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --no-progress -y

      - name: Build Windows Installer (Inno Setup)
        shell: powershell
        run: |
          $iscc = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          & $iscc installer.iss
          if (!(Test-Path .\Output\SecurePasteP2P-Lilac-Setup.exe)) {
            throw "Installer not found at Output\\SecurePasteP2P-Lilac-Setup.exe"
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SecurePasteP2P-Windows
          path: |
            dist/SecurePasteP2P.exe
            Output/SecurePasteP2P-Lilac-Setup.exe

      - name: Create release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/SecurePasteP2P.exe
            Output/SecurePasteP2P-Lilac-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
