name: Release (Windows)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write   # needed to create/upload a release

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build portable EXE (PyInstaller)
        shell: powershell
        run: |
          # change secure.py if your entry file has a different name
          pyinstaller `
            --noconfirm `
            --onefile `
            --windowed `
            --icon app.ico `
            --name SecurePasteP2P `
            secure.py
          Get-ChildItem dist

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --no-progress -y

      - name: Build Installer (Inno Setup)
        shell: powershell
        run: |
          # Assumes installer.iss is configured to read dist\SecurePasteP2P.exe
          $iscc = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          & $iscc installer.iss
          if (!(Test-Path .\Output)) { throw "Inno Setup did not produce an Output folder." }
          Get-ChildItem .\Output

      - name: Create checksums (optional)
        shell: powershell
        run: |
          Get-FileHash dist\SecurePasteP2P.exe -Algorithm SHA256 | Format-List > SHA256SUMS.txt
          if (Test-Path .\Output) {
            Get-FileHash (Get-ChildItem .\Output\*.exe | Select-Object -First 1) -Algorithm SHA256 | Format-List >> SHA256SUMS.txt
          }

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SecurePasteP2P-Windows
          path: |
            dist/SecurePasteP2P.exe
            Output/*.exe
            SHA256SUMS.txt
          if-no-files-found: error

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/SecurePasteP2P.exe
            Output/*.exe
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
